name: Monitor Voos (AviationStack) e Enviar WhatsApp

on:
  schedule:
    - cron: "*/30 * * * *"  # a cada 30 minutos
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          CALLMEBOT_PHONE: ${{ secrets.CALLMEBOT_PHONE }}
          CALLMEBOT_APIKEY: ${{ secrets.CALLMEBOT_APIKEY }}
          AVIATIONSTACK_KEY: ${{ secrets.AVIATIONSTACK_KEY }}
        run: python flights.py
